#!/bin/bash

CMD="npm run build"

#run the prepush command and check the result
$CMD
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "failed $CMD"
	exit 1
fi

CMD_ADD="git add dist/* index.html"

$CMD_ADD
$CMD_COMMIT

exit 0
