export enum Event {
    SPACE_INITIALIZED,
    ADD_TICKER,
    ADD_DISPLAY_OBJECT,

    // Space interactions
    SPACE_POINTER_MOVE,
    SPACE_POINTER_OUT,

    SPACE_BUTTON_HOVER,
    SPACE_BUTTON_OUT,

    START_BUTTON_CLICK,
}
